### ISSUE TITLE
PR Actions don't re-trigger when pushing new commits

### ISSUE THREAD

**Issue by gary-roach** [redstreet/beancount_reds_importers#114]
The pull request Actions run when creating the PR initially, but they don't re-run when you push a new commit to fix something found in the initial quality gate. 

I think it's likely because the [workflow definition](.github/workflows/pythonpackage.yml) doesn't have the type of "synchronize". This [community issue](https://github.com/orgs/community/discussions/25796) states that it's necessary in order for actions to re-run when additional commits are pushed. They state that the edited type applies to changes to the title, body, state, base, etc... but not commits. 

Is the intent for the actions to re-run if additional commits are pushed?

**Comment by redstreet** [comment]
> Is the intent for the actions to re-run if additional commits are pushed?

Yes indeed. Thank you for catching this and finding the fix. Committing in a second.
