### ISSUE TITLE
Add support for commodity and account entries.

### ISSUE THREAD

**Issue by savingsandloan** [redstreet/beancount_reds_importers#30]
The proposed changes would add support for Commodity & Account entries

- Readers: Add `get_commodity_entries` and `get_account_entries` methods to readers (ofxreader, csvreader, csv_multitable_reader)
- Common Importers: Add configurable checks of `self.include_commodities` and `self.include_accounts` to investments.py (any other relevant importers?)
- Common Importers: Add `extract_commodities` and `extract_accounts` methods that would be called within `extract` if associated `include_` is set to true.

An earlier approach to this in `fidelity_csv_old` was commits:
- https://github.com/savingsandloan/beancount_reds_importers/commit/c17331fac435b31eec6b6acef72ed639e0ef57cd
- https://github.com/savingsandloan/beancount_reds_importers/commit/a71331319bc8a977776bea29959ab588a862e53a

It would largely be the same except of course carry the new approach to build_metadata as done in https://github.com/redstreet/beancount_reds_importers/pull/28

**Comment by redstreet** [comment]
Thanks, this helps! How about [this commit](https://github.com/redstreet/beancount_reds_importers/commit/1cd7e123b9dd3118e394e64f22dcd43c9ff4b2d5) instead? Would it solve all your needs? If so, I can add it to banking and paychecks as well.

**Comment by savingsandloan** [comment]
Technically should. It does introduce some questions of why other libreader methods (e.g. `get_balance_positions`) are there (and leads to questions around the framing around ofx), but let me see how this works.

**Comment by redstreet** [comment]
Merged to main.
