### ISSUE TITLE
bean-download dependency on click_aliases

### ISSUE THREAD

**Issue by thusspokecolton** [redstreet/beancount_reds_importers#31]
With the latest addition of bean-download and the `from click_aliases import ClickAliasedGroup` in util/bean_ingest.py, does click_aliases need to be added as a dependency here?
https://github.com/redstreet/beancount_reds_importers/blob/main/requirements.txt

**Comment by redstreet** [comment]
Indeed, and it also had to be added here, which I've both done, and made a Pypi release:
https://github.com/redstreet/beancount_reds_importers/blob/main/setup.py

Thanks for filing this issue! For some reason, this issue didn't send me an email (strange), else I'd have responded earlier.
