### ISSUE TITLE
QOL CUSIP number search?

### ISSUE THREAD

**Issue by dustinfarris** [redstreet/beancount_reds_importers#4]
Do I have to do something special to get a CUSIP # from QOL?

I tried searching Vanguard's VTWAX and getting nothing.  Also noticed that one of the CUSIP #'s in the example fund_info.py comes up not found on QOL.  Am I doing it wrong?

**Comment by redstreet** [comment]
VTWAX is a mutual fund, and mutual funds are not exchange traded. This is why they are not shown in QOL. So you'd have to look them up at Vanguard. Searching there brings up [this page](https://investor.vanguard.com/mutual-funds/profile/VTWAX) which has the CUSIP listed. Hope that helped clear it up :).

This is not clear in `fund_info.py`. I just updated the doc in fe97d6253142c410654201055495a685b9d89b3a. Does that make it clearer? Feel free to submit a PR if not.
