### ISSUE TITLE
"Not supported" in csvreader.py

### ISSUE THREAD

**Issue by flowerbug** [redstreet/beancount_reds_importers#48]
hello, this is "Fin" from the beancount forum.

I've hit this error message even when I have:

        self.include_balances = False

    defined in my custom init for the csv converter.

To temporarily get around it I've changed the raise error to be commented out and returned (()) instead.  If I simply say pass it will error because it wanted something back.

My data file that I'm testing at the moment has no balance assertions or any positions as it is only a small part I'm working on for testing my tdameritrade csv importer.

I'm sure I could also be doing something else wrong, but at least with this fix I can get output for where I am at for now.  :)

**Comment by redstreet** [comment]
Fixed, thanks for filing! Please update to the latest version on git (not on PyPI).

Note `include_balances` hasn't been a supported option any more. You can simply remove that line in your code, and it should work fine now.
