### ISSUE TITLE
Some small fixes needed.

### ISSUE THREAD

**Issue by flowerbug** [redstreet/beancount_reds_importers#49]
Instead of opening an issue for each is it ok to list them in one place like this?

Well if this offends you or you'd like it another way I'll change for the next time.  :)

1. two links in the README.md give 404 errors 

 "See working examples of an [ofx based](https://github.com/redstreet/beancount_reds_importers/blob/main/beancount_reds_importers/citi/__init__.py) and [csv](https://github.com/redstreet/beancount_reds_importers/blob/main/beancount_reds_importers/schwab_csv/__init__.py) based importers."

2. the example directory does not run (likely due to import and name changes).

**Comment by redstreet** [comment]
Totally okay to list them here: they're small, and non-code related :).

Thanks a bunch for filing this! Fixed.

**Comment by flowerbug** [comment]
:)  I'm glad I can help out even if it is in small ways at the moment.

**Comment by flowerbug** [comment]
I notice you do not have a discussion spot.  I'm not sure if you want yet another place to look for things, but it would be good to be able to ask and get answers to more general issues.

**Comment by redstreet** [comment]
For now, I'd rather have these discussions in the [Beancount groups](https://groups.google.com/g/beancount/) and/[or my site](https://reds-rants.netlify.app/) so these these are visible to folks who may not know about these importers but are needing them.

But you raise a good point, I should probably put a pointer to the groups in the README/md. Done.

**Comment by flowerbug** [comment]
I'm not sure if you know about usenet, but that is how I read/write to the group you mention.  That group is known as gmane.comp.finance.beancount which then passes it along to google groups (and back).

**Comment by redstreet** [comment]
Yes, I use gmane.
