### ISSUE TITLE
Missing dependency: petl

### ISSUE THREAD

**Issue by maxalbert** [redstreet/beancount_reds_importers#6]
Many thanks @redstreet for making these importer tools available.

I tried to run the example importer in `beancount_reds_importers/example` (in a fresh virtual environment) but got the following error.
```
$ bean-identify my.import OfxDownload.qfx 
[...]
ModuleNotFoundError: No module named 'petl'
```
Looks like `petl` needs to be added as a dependency in `setup.py`?

**Comment by redstreet** [comment]
Happy you're finding it useful. Indeed, I'd forgotten `petl` as a dependency. Fixed, thank you!
