### ISSUE TITLE
Add 'Qualified Dividend` Schwab Brokerage CSV Action

### ISSUE THREAD

**Issue by doughepi** [redstreet/beancount_reds_importers#60]
`Qualified Dividend` is another Schwab Brokerage CSV action that should be supported by this library.

Example Record
```
"Date","Action","Symbol","Description","Quantity","Price","Fees & Comm","Amount"
"02/01/2023","Qualified Dividend","GIS","GENERAL MILLS INC","","","","$0.54"
```

Should just be treated as a `reds_importer` `dividend` type. 

Let me know! I could add this myself but I won't be able to get to it for a bit! Also blocked by #59.

**Comment by redstreet** [comment]
Added, thanks!

Good to know Schwab distinguishes between qualified and non-qualified dividends. You can take advantage of this by automating the booking of it to a qualified account [as shown here](https://reds-rants.netlify.app/personal-finance/customizing-your-importer/), if you are ever interested in using Beancount to [compute your taxes](https://reds-rants.netlify.app/personal-finance/computing-taxes-with-beancount/).
