### ISSUE TITLE
file_date fails if there are no accounts in the OFX file

### ISSUE THREAD

**Issue by doughepi** [redstreet/beancount_reds_importers#61]
Ran into the following issue while trying to use the import page in Fava. Error comes from their API:

```json
{
    "error": "Error calling importer method: 'NoneType' object has no attribute 'statement'",
    "success": false
}
```

Tracked the error down with PDB to the line 

```txt
> /Users/me/Library/Mobile Documents/com~apple~CloudDocs/Personal/Code/finances/venv/lib/python3.9/site-packages/beancount_reds_importers/libreader/ofxreader.py(41) 
file_date() -> return self.ofx_account.statement.end_date
(Pdb) list
 36             the full account number. Override this method to handle these cases."""
 37             return file_account == config_account
 38  
 39         def file_date(self, file):
 40             "Get the maximum date from the file."
 41  ->         return self.ofx_account.statement.end_date
 42  
```

[Finding this in source](https://github.com/redstreet/beancount_reds_importers/blob/fac2c2bbd5dccae3113e9f41ef27b455db8bedef/beancount_reds_importers/libreader/ofxreader.py#LL41C51-L41C51) identifies that it is never checked if `ofx_account` is `None` after the logic in the `__init__`.

I suspect this is a quirk of Chase QFX files. Perhaps there is a better way of getting the latest date in the file?

**Comment by redstreet** [comment]
Good to know! I don't use Fava's import, so this is good data to have. Please try the fix above. You can use this to install:
```
pip3 install git+https://github.com/redstreet/beancount_reds_importers
```

If that too crashes for your use case, if you could send me an anonymized `.ofx` file, I can provide a fix.

Thanks for filing 👍.

**Comment by doughepi** [comment]
That was it! Thanks for the extremely fast turnaround :)

**Comment by redstreet** [comment]
Great!

Thanks for doing most of the work in identifying the source of the issue---which makes it easy for me turn it around quickly :).
