### ISSUE TITLE
Balance entries malformed

### ISSUE THREAD

**Issue by doughepi** [redstreet/beancount_reds_importers#62]
The Fava API was having trouble jsonifying imports. Turns out it was because of a single `count` object that made its way into metadata for balance entries. I looked at the data it was attempting to run through `json.dumps` and saw this:

```python
    transaction = {
        "meta": {
            "filename": "ChaseXXXX....QFX",
            "lineno": count(250),
        },
        "date": datetime.date(2023, 5, 5),
        "account": "Liabilities:Current-Liabilities:Credit-Cards:Chase:Sapphire-Reserve",
        "amount": {"number": "-5442.48", "currency": "USD"},
        "tolerance": None,
        "diff_amount": None,
        "type": "Balance",
    }
````

I suspect it's because `next()` isn't being used on [this metadata initialization](
https://github.com/redstreet/beancount_reds_importers/blob/9a9d64ad24f16f62b1a292c66629d4e0bf511a48/beancount_reds_importers/libtransactionbuilder/banking.py#LL80C57-L80C64)

Suspected fix is to do `next(counter)`.

edit: tested this fix on my machine--works!

**Comment by redstreet** [comment]
Great, thanks for finding these bugs, and for trying out the fix :). I don't use imports via Fava, so this is helpful.

**Comment by bearbin** [comment]
Thanks for the fix! I was just about to create a report for this, but it was already taken care of :)

For the search-bots, this is the error message produced by Fava:

    TypeError: Object of type count is not JSON serializable
