### ISSUE TITLE
Numerical fixes for UOB importer

### ISSUE THREAD

**Issue by kaiwei** [redstreet/beancount_reds_importers#70]
1. "Cash Withdrawal" entries should have 2 decimal places even for whole numbers but are currently missing. This affects automatic numerical display inference in Fava
2. Entries should mirror numerical precision from exported Excel bank source, which are to 2 decimal places. But this seems to be rounded down (now) plus the numerical precision seems to go out to several lengthy number of places (which also somehow crashes fava)
3. Importer outputs a warning message to terminal line when ran: "WARNING *** file size (92598) not 512 + multiple of sector size (512)"
4. Last minor nit tweak: Possible to output the larger positive numberical figures, e.g., 1,000, as it is, without commas (i.e, 1000)? Commas rendering should be something adjustable in fava, etc., but not part of the raw beancount output?

**Comment by redstreet** [comment]
@kaiwei would you mind attaching anonymized data and expected output? This will help debug and become unit tests to prevent regressions. Thanks!

**Comment by kaiwei** [comment]
I had emailed them to you (earlier) the raw actual files (given privacy concerns). Hope that's okay!

**Comment by redstreet** [comment]
I totally understand, anonymizing data is a pain. But if you could post even minimal anonymized data here that I can commit to the repository as tests (eg: a single transaction for each issue here), that would be of great help in ensuring things don't break in the future.

IMHO, this is a good opportunity to build and commit tests. Continuing to build and make fixes without unit tests rarely has good outcomes, and I'm simply trying to ensure we end up with a solid, stable codebase with these importers.

I hope that makes sense? Happy to discuss more if needed.

**Comment by kaiwei** [comment]
No problems. I'll get to it for the purpose of the tests, but hopefully the actual files (which were emailed) are useful to you in the meantime.

Appreciate the help as always.

**Comment by redstreet** [comment]
Sounds great, thanks much! If it's okay, I'll wait to receive the data to commit the fix to avoid duplication of effort.

**Comment by kaiwei** [comment]
Here you go!

[uniplus.zip](https://github.com/redstreet/beancount_reds_importers/files/11954266/uniplus.zip)

Simple config
    apply_hooks(uobbank.Importer({
        'main_account'   : 'Assets:Banks:UOB:UNIPLUS',
        'account_number' : '1234567890',
        'currency'       : 'SGD',
        'rounding_error' : 'Equity:Rounding-Errors:Imports',
        }), [PredictPostings()]),

**Comment by redstreet** [comment]
> 1. "Cash Withdrawal" entries should have 2 decimal places even for whole numbers but are currently missing. This affects automatic numerical display inference in Fava

Fixed. Still needs a full solution. The problem is, petel uses xlwt/xlrd to read excel, which use excel datatypes, which we don't want, as we want just the string, which we can then pass on to decimal.decimal. Not sure exactly how decimals are stored in excel

It should have a single digit after the decimal. Please let me know if this solves your issue?

> 2. Entries should mirror numerical precision from exported Excel bank source, which are to 2 decimal places. But this seems to be rounded down (now) plus the numerical precision seems to go out to several lengthy number of places (which also somehow crashes fava)

Fixed.

> 3. Importer outputs a warning message to terminal line when ran: "WARNING *** file size (92598) not 512 + multiple of sector size (512)"

Fixed.

> 4. Last minor nit tweak: Possible to output the larger positive numberical figures, e.g., 1,000, as it is, without commas (i.e, 1000)? Commas rendering should be something adjustable in fava, etc., but not part of the raw beancount output?

Thousands separator-in-source seem to be an issue of personal preference. It does make the source readable, and some like it for that. Others don't or don't care.

I'll leave it the way it is to have it remain consistent with `beancount_reds_importers`. But changing this at your end is trivial: simply run use [autobean-format](https://github.com/SEIAROTg/autobean-format) on your source, or pipe the import through it:
```
autobean-format foo.bean --thousands-separator=add --recursive --output-mode inplace
```

**Comment by kaiwei** [comment]
Thanks for the autobean recommendation! It's a great formatter!

**Comment by redstreet** [comment]
That's the part above I referred to as arising from petl using xlwt/xlrd to read excel, and not yet fully resolved. It might require a bit of digging and time to figure out. I'll do it when I get some time next, but it might be a while.

**Comment by kaiwei** [comment]
Aha got it. Thank you for the help!

**Comment by redstreet** [comment]
Piping through a simple sed should fix the issue until resolved.

**Comment by redstreet** [comment]
Remaining issue will be covered by #74.
