### ISSUE TITLE
Import both legs of postings.

### ISSUE THREAD

**Issue by jahagirdar** [redstreet/beancount_reds_importers#86]
My csv file has the following Columns
Date,Transaction Title,Amount,Paid from Account,Credit to Account,Receipt

e.g.
20/04/2019,Fuel,1000,BankCard,Travel,https://drive.google.com/image_url

In my custom_init I am setting header_map to
 'Date': 'date',
 'Transaction Title': 'memo',
 'Amount': 'Amount',

How should I map the remaining 3 columns?

**Comment by redstreet** [comment]
What would you like the result to be? If you want to ignore them, no need to do anything further.

**Comment by jahagirdar** [comment]
I eventually want it to be

```
2019-04-20 * "Fuel"
    Assets:INR:BankCard -1000 INR
    Expenses:INR:Travel
    document "https://drive.google.com/image_url"
```

**Comment by redstreet** [comment]
See https://github.com/redstreet/beancount_reds_importers/blob/5cadec2ce80c99f276a7c218539a117898d4885b/beancount_reds_importers/importers/workday/__init__.py#L51-L52
