### ISSUE TITLE
Change in Schwab checking header breaks importer

### ISSUE THREAD

**Issue by chase-dwelle** [redstreet/beancount_reds_importers#91]
When doing my last update, I noticed the header for Schwab's checking CSV has changed, which breaks the importer.

I just modified the header and CSV file in order to use the current importer, but going forward the Checking CSV importer should change.

The old header:
```
"Transactions  for Checking account ...XXX as of 09/02/2023 01:46:01 PM ET"
"Date","Type","Check #","Description","Withdrawal (-)","Deposit (+)","RunningBalance"
"Pending Transactions are not reflected within this sort criterion."
"Posted Transactions"
```
The new header:
```
"Date","Status","Type","CheckNumber","Description","Withdrawal","Deposit","RunningBalance"
```

I can make the changes to the importer the next time I update my ledger and put in a PR, but also flagging this here in case others run into the same issue.

**Comment by redstreet** [comment]
Thank you for reporting this, fixed!

Schwab also now offers json and xml. We should eventually kill the csv importer in favor of those since they are far more stable formats.

**Comment by redstreet** [comment]
The unit test needs to be fixed. I'll get to it eventually, but if you have a chance to fix it before I do, I would appreciate a PR. Thank you!
