### ISSUE TITLE
import.sh failure

### ISSUE THREAD

**Issue by mattmccormick** [redstreet/beancount_reds_importers#92]
In the examples/ directory, the my-smart.importer references the `smart_importer` package that doesn't exist.  Perhaps it was removed in the past?

This .import file is referenced in the `import.sh` script which is mentioned in the `README` to run the examples.

Additionally, running `bean-identify my.import transactions.qfx` does not seem to match any Importers.

**Comment by redstreet** [comment]
It requires you to to have `smart_importer` installed. `bean-identify my-smart.import transactions.qfx` then works. Clarified in the README. Thanks.
